# Generated by Django 5.1.1 on 2024-11-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_orderitem_product_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
