# Generated by Django 5.1.1 on 2024-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productreview_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
